"""added a new like table

Revision ID: 0abd6504515a
Revises: 6038b58c0e36
Create Date: 2026-04-17 11:51:27.869940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0abd6504515a'
down_revision: Union[str, Sequence[str], None] = '6038b58c0e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_type',
               existing_type=postgresql.ENUM('student', 'teacher', name='usertypeenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_type',
               existing_type=postgresql.ENUM('student', 'teacher', name='usertypeenum'),
               nullable=True)
    # ### end Alembic commands ###
