"""add role and user_type

Revision ID: 6038b58c0e36
Revises: 
Create Date: 2026-04-14 13:11:14.743340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6038b58c0e36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1️⃣ Add columns as nullable
    op.add_column(
        'users',
        sa.Column('role', sa.Enum('ADMIN', 'USER', 'STAFF', name='userrole'), nullable=True)
    )
    op.add_column(
        'users',
        sa.Column('user_type', sa.Enum('student', 'teacher', name='usertypeenum'), nullable=True)
    )

    # 2️⃣ Backfill existing data
    op.execute("UPDATE users SET role = 'USER' WHERE role IS NULL")

    # 3️⃣ Enforce NOT NULL (for role only)
    op.alter_column('users', 'role', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
